from typing import List, Dict, Any

INITIAL_HOSTS = [
    {
        "id": "web-server",
        "hostname": "web-server",
        "ip_address": "10.0.0.10",
        "host_type": "WEB",
        "status": "HEALTHY",
        "criticality": "HIGH",
    },
    {
        "id": "server-01",
        "hostname": "server-01",
        "ip_address": "10.0.1.10",
        "host_type": "APP",
        "status": "HEALTHY",
        "criticality": "MEDIUM",
    },
    {
        "id": "server-02",
        "hostname": "server-02",
        "ip_address": "10.0.1.11",
        "host_type": "APP",
        "status": "HEALTHY",
        "criticality": "MEDIUM",
    },
    {
        "id": "server-03",
        "hostname": "server-03",
        "ip_address": "10.0.1.12",
        "host_type": "APP",
        "status": "HEALTHY",
        "criticality": "HIGH",
    },
    {
        "id": "database",
        "hostname": "database",
        "ip_address": "10.0.2.10",
        "host_type": "DATABASE",
        "status": "HEALTHY",
        "criticality": "CRITICAL",
    },
]

SCENARIOS: Dict[str, Dict[str, Any]] = {
    "credential_compromise": {
        "id": "credential_compromise",
        "name": "Credential Compromise",
        "target_host": "server-01",
        "source_ip": "192.0.2.42",
        "events": [
            {
                "tick": 1,
                "timestamp": "10:32:01",
                "event_type": "FAILED_LOGIN",
                "severity": "LOW",
                "target_host": "server-01",
                "source_ip": "192.0.2.42",
                "details": {"username": "admin", "attempt_count": 1, "location": "192.0.2.42"},
            },
            {
                "tick": 2,
                "timestamp": "10:32:04",
                "event_type": "FAILED_LOGIN",
                "severity": "LOW",
                "target_host": "server-01",
                "source_ip": "192.0.2.42",
                "details": {"username": "admin", "attempt_count": 2, "location": "192.0.2.42"},
            },
            {
                "tick": 3,
                "timestamp": "10:32:07",
                "event_type": "FAILED_LOGIN",
                "severity": "MEDIUM",
                "target_host": "server-01",
                "source_ip": "192.0.2.42",
                "details": {"username": "admin", "attempt_count": 3, "location": "192.0.2.42"},
            },
            {
                "tick": 4,
                "timestamp": "10:32:10",
                "event_type": "SUCCESSFUL_LOGIN",
                "severity": "MEDIUM",
                "target_host": "server-01",
                "source_ip": "192.0.2.42",
                "details": {"username": "admin", "auth_method": "password", "session_id": "sess-8842"},
            },
            {
                "tick": 5,
                "timestamp": "10:32:15",
                "event_type": "SUSPICIOUS_LOGIN",
                "severity": "HIGH",
                "target_host": "server-01",
                "source_ip": "192.0.2.42",
                "details": {"username": "admin", "country": "Unknown/Tor", "ip": "192.0.2.42"},
            },
            {
                "tick": 6,
                "timestamp": "10:32:20",
                "event_type": "PRIVILEGE_ESCALATION",
                "severity": "HIGH",
                "target_host": "server-01",
                "source_ip": "192.0.2.42",
                "details": {"username": "admin", "privilege_level": "root/sudo", "command": "usermod -aG sudo admin"},
            },
            {
                "tick": 7,
                "timestamp": "10:32:30",
                "event_type": "SENSITIVE_FILE_ACCESS",
                "severity": "CRITICAL",
                "target_host": "server-01",
                "source_ip": "192.0.2.42",
                "details": {"username": "admin", "resource": "/etc/shadow", "action": "read"},
            },
        ],
    },
    "ransomware": {
        "id": "ransomware",
        "name": "Ransomware Simulation",
        "target_host": "server-03",
        "source_ip": "192.0.2.66",
        "events": [
            {
                "tick": 1,
                "timestamp": "10:32:01",
                "event_type": "FAILED_LOGIN",
                "severity": "LOW",
                "target_host": "server-03",
                "source_ip": "192.0.2.66",
                "details": {"username": "sysadmin", "attempt_count": 1, "service": "ssh"},
            },
            {
                "tick": 2,
                "timestamp": "10:32:03",
                "event_type": "FAILED_LOGIN",
                "severity": "LOW",
                "target_host": "server-03",
                "source_ip": "192.0.2.66",
                "details": {"username": "sysadmin", "attempt_count": 2, "service": "ssh"},
            },
            {
                "tick": 3,
                "timestamp": "10:32:06",
                "event_type": "SUCCESSFUL_LOGIN",
                "severity": "MEDIUM",
                "target_host": "server-03",
                "source_ip": "192.0.2.66",
                "details": {"username": "sysadmin", "service": "ssh", "session_id": "sess-9912"},
            },
            {
                "tick": 4,
                "timestamp": "10:32:10",
                "event_type": "PRIVILEGE_ESCALATION",
                "severity": "HIGH",
                "target_host": "server-03",
                "source_ip": "192.0.2.66",
                "details": {"username": "sysadmin", "vector": "sudo_exploit", "target_uid": 0},
            },
            {
                "tick": 5,
                "timestamp": "10:32:14",
                "event_type": "SERVER_ACCESS",
                "severity": "MEDIUM",
                "target_host": "server-03",
                "source_ip": "192.0.2.66",
                "details": {"username": "root", "target_server": "server-03", "protocol": "smb/rpc"},
            },
            {
                "tick": 6,
                "timestamp": "10:32:18",
                "event_type": "SENSITIVE_FILE_ACCESS",
                "severity": "HIGH",
                "target_host": "server-03",
                "source_ip": "192.0.2.66",
                "details": {"directory": "/var/data/backups", "files_accessed": 150},
            },
            {
                "tick": 7,
                "timestamp": "10:32:25",
                "event_type": "MASS_FILE_MODIFICATION",
                "severity": "CRITICAL",
                "target_host": "server-03",
                "source_ip": "192.0.2.66",
                "details": {"action": "encrypt", "extension": ".locked", "modified_count": 4820},
                "host_state_change": {"host_id": "server-03", "new_status": "COMPROMISED"},
            },
        ],
    },
    "data_exfiltration": {
        "id": "data_exfiltration",
        "name": "Data Exfiltration",
        "target_host": "database",
        "source_ip": "192.0.2.99",
        "events": [
            {
                "tick": 1,
                "timestamp": "10:32:01",
                "event_type": "SUSPICIOUS_LOGIN",
                "severity": "MEDIUM",
                "target_host": "database",
                "source_ip": "192.0.2.99",
                "details": {"db_user": "db_analytics", "client_ip": "192.0.2.99", "anomaly": "off_hours"},
            },
            {
                "tick": 2,
                "timestamp": "10:32:10",
                "event_type": "SENSITIVE_FILE_ACCESS",
                "severity": "HIGH",
                "target_host": "database",
                "source_ip": "192.0.2.99",
                "details": {"table": "customer_pii", "query": "SELECT * FROM customer_pii", "rows_fetched": 50000},
            },
            {
                "tick": 3,
                "timestamp": "10:32:20",
                "event_type": "DATA_AGGREGATION",
                "severity": "HIGH",
                "target_host": "database",
                "source_ip": "192.0.2.99",
                "details": {"action": "staging_dump", "compressed_size_mb": 1250, "location": "/tmp/dump.tar.gz"},
            },
            {
                "tick": 4,
                "timestamp": "10:32:35",
                "event_type": "LARGE_OUTBOUND_TRANSFER",
                "severity": "CRITICAL",
                "target_host": "database",
                "source_ip": "192.0.2.99",
                "details": {"destination": "192.0.2.99", "bytes_transferred": 1310720000, "protocol": "HTTPS"},
            },
        ],
    },
}
